// import { createAsyncThunk } from "@reduxjs/toolkit";
// import UseRequest from "../../Hook/useRequest";

// const {get} = UseRequest()
// export const fetchClothesData = createAsyncThunk("clothes/fetchClothesData", async() => {
//     const res = await get("https://run.mocky.io/v3/9fd8f710-246d-40f8-b67e-3595c2f9672a");
//     return res;
// });

export const clothesDatabase = [
    {
      "id": 1,
      "price": 5050,
      "category": "Anoraks",
      "color": "black",
      "description": "Avalanche Armor Parka",
      "gender": "male",
      "article": "03802",
      "sale": true,
      "favorites": false,
      "image": "https://i.imgur.com/rBt0oOG.jpeg"
    },
    {
      "id": 2,
      "price": 5940,
      "category": "Anoraks",
      "color": "black",
      "description": "Arctic Shield Anorak",
      "gender": "male",
      "article": "03803",
      "sale": true,
      "favorites": false,
      "image": "https://i.imgur.com/rBt0oOG.jpeg"
    },
    {
      "id": 3,
      "price": 6380,
      "category": "Anoraks",
      "color": "black",
      "description": "Frostbound Parka",
      "gender": "male",
      "article": "03804",
      "sale": true,
      "favorites": false,
      "image": "https://i.imgur.com/rBt0oOG.jpeg"
    },
    {
      "id": 4,
      "price": 5640,
      "category": "Anoraks",
      "color": "black",
      "description": "Snowstorm Sentinel Anorak",
      "gender": "male",
      "article": "03805",
      "sale": true,
      "favorites": false,
      "image": "https://i.imgur.com/rBt0oOG.jpeg"
    },
    {
      "id": 5,
      "price": 6150,
      "category": "Anoraks",
      "color": "black",
      "description": "Arctic Shield Anorak",
      "gender": "male",
      "article": "03806",
      "sale": true,
      "favorites": false,
      "image": "https://i.imgur.com/rBt0oOG.jpeg"
    },
    {
      "id": 6,
      "price": 6930,
      "category": "Anoraks",
      "color": "black",
      "description": "Arctic Shield Anorak",
      "gender": "male",
      "article": "03807",
      "sale": false,
      "favorites": false,
      "image": "https://i.imgur.com/rBt0oOG.jpeg"
    },
    {
        "id": 7,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
    },
    {
        "id": 8,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 9,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 10,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 11,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 12,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 13,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 14,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 15,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 16,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 17,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 18,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 19,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 20,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 21,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 22,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 23,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 24,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 25,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      ,
      {
        "id": 26,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 27,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 28,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 29,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 30,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 31,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 32,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 33,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 34,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 35,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      ,
      {
        "id": 36,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 37,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 38,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 39,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 40,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 41,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 42,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 43,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 44,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 45,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      ,
      {
        "id": 46,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 47,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 48,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 49,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 50,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 51,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 52,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 53,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 54,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 55,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      ,
      {
        "id": 56,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 57,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 58,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 59,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 60,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 61,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 62,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 63,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 64,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 65,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      ,
      {
        "id": 66,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 67,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 68,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 69,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 70,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 71,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 72,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 73,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 74,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 75,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      ,
      {
        "id": 76,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 77,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 78,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 79,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 80,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 81,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 82,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 83,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 84,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 85,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      ,
      {
        "id": 86,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 87,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 88,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 89,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 90,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 91,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 92,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 93,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 94,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 95,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      ,
      {
        "id": 96,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 97,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 98,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 99,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 100,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 101,
        "price": 5050,
        "category": "Anoraks",
        "color": "black",
        "description": "Avalanche Armor Parka",
        "gender": "male",
        "article": "03802",
        "sale": true,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 102,
        "price": 5940,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03803",
        "sale": true,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 103,
        "price": 6380,
        "category": "Anoraks",
        "color": "black",
        "description": "Frostbound Parka",
        "gender": "male",
        "article": "03804",
        "sale": true,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 104,
        "price": 5640,
        "category": "Anoraks",
        "color": "black",
        "description": "Snowstorm Sentinel Anorak",
        "gender": "male",
        "article": "03805",
        "sale": true,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 105,
        "price": 6150,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03806",
        "sale": true,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
        "id": 106,
        "price": 6930,
        "category": "Anoraks",
        "color": "black",
        "description": "Arctic Shield Anorak",
        "gender": "male",
        "article": "03807",
        "sale": false,
        "favorites": false,
        "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
          "id": 107,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
      },
      {
          "id": 108,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 109,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 110,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 111,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 112,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 113,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 114,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 115,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 116,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 117,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 118,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 119,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 120,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 121,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 122,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 123,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 124,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 125,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        ,
        {
          "id": 126,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 127,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 128,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 129,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 130,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 131,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 132,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 133,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 134,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 135,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        ,
        {
          "id": 136,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 137,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 138,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 139,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 140,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 141,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 142,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 143,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 144,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 145,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        ,
        {
          "id": 146,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 147,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 148,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 149,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 150,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 151,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 152,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 153,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 154,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 155,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        ,
        {
          "id": 156,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 157,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 158,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 159,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 160,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 161,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 162,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 163,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 164,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 165,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        ,
        {
          "id": 166,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 167,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 168,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 169,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 170,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 171,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 172,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 173,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 174,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 175,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        ,
        {
          "id": 176,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 177,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 178,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 179,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 180,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 181,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 182,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 183,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 184,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 185,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        ,
        {
          "id": 186,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 187,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 188,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 189,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 190,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 191,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 192,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 193,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 194,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 195,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        ,
        {
          "id": 196,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 197,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 198,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 199,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        },
        {
          "id": 200,
          "price": 6930,
          "category": "Anoraks",
          "color": "black",
          "description": "Arctic Shield Anorak",
          "gender": "male",
          "article": "03807",
          "sale": false,
          "favorites": false,
          "image": "https://i.imgur.com/rBt0oOG.jpeg"
        }
]